version: "3"

services:
  # wholeapp:
  #   build: .
  #   depends_on:
  #     - gateway_db
  #     - group_service_db
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #     - .env
  #   environment:
  #     - GATEWAY_DB_HOST=gateway_db
  #     - GATEWAY_DB_PORT=5432
  #     - GATEWAY_DB_NAME=${GATEWAY_POSTGRES_USER}
  #     - GATEWAY_DB_USERNAME=${GATEWAY_POSTGRES_USER}
  #     - GATEWAY_DB_PASS=${GATEWAY_POSTGRES_PASSWORD}
  #     - GROUP_SERVICE_HOST=localhost
  #     - GROUP_SERVICE_PORT=8081

  #     - GROUP_LISTEN_ADDR=localhost:8081
  #     - GROUP_DB_HOST=group_service_db
  #     - GROUP_DB_PORT=5435
  #     - GROUP_DB_NAME=${GROUP_POSTGRES_USER}
  #     - GROUP_DB_USERNAME=${GROUP_POSTGRES_USER}
  #     - GROUP_DB_PASS=${GROUP_POSTGRES_PASSWORD}
  #   ports:
  #     - 8080:8080
  #   command: go run app/cmd/main.go

  #  gateway:
  #    build: ./app
  #    depends_on:
  #      - gateway_db
  #    volumes:
  #      - .:/usr/src/app
  #    env_file:
  #      - .env
  #    environment:
  #      - GATEWAY_DB_HOST=gateway_db
  #      - GATEWAY_DB_PORT=5432
  #      - GATEWAY_DB_NAME=${GATEWAY_POSTGRES_USER}
  #      - GATEWAY_DB_USERNAME=${GATEWAY_POSTGRES_USER}
  #      - GATEWAY_DB_PASS=${GATEWAY_POSTGRES_PASSWORD}
  #      - GROUP_SERVICE_HOST=group_service
  #      - GROUP_SERVICE_PORT=8081
  #      - LOGLEVEL=debug
  #    ports:
  #      - "8081:8081"
  #    command: go run app/cmd/main.go

  gateway_db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${GATEWAY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${GATEWAY_POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    # volumes:
    #   - .:/var/lib/postgresql/data

  gateway_db_migrate:
    image: migrate/migrate
    depends_on:
      - gateway_db
    env_file:
      - .env
    volumes:
      - ./app/internal/adapter/db/migration:/migrations
    command:
      [
        "-path",
        "/migrations/",
        "-database",
        "postgres://${GATEWAY_POSTGRES_USER}:${GATEWAY_POSTGRES_PASSWORD}@gateway_db:5432/${GATEWAY_POSTGRES_USER}?sslmode=disable",
        "up",
      ]

  # group_service:
  #   build: ./group_service
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - group_service_db
  #   volumes:
  #     - .:/usr/src/app
  #   env_file:
  #     - .env
  #   environment:
  #     - GROUP_LISTEN_ADDR=group_service:8081
  #     - GROUP_DB_HOST=group_service_db
  #     - GROUP_DB_PORT=5432
  #     - GROUP_DB_NAME=${GROUP_POSTGRES_USER}
  #     - GROUP_DB_USERNAME=${GROUP_POSTGRES_USER}
  #     - GROUP_DB_PASS=${GROUP_POSTGRES_PASSWORD}
  #   command: go run group_service/cmd/main.go

  # group_service_db:
  #   image: postgres:alpine
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_USER=${GROUP_POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${GROUP_POSTGRES_PASSWORD}
  #   ports:
  #     - 5433:5432

  # group_service_db_migrate:
  #   image: migrate/migrate
  #   depends_on:
  #     - group_service_db
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./group_service/internal/adapter/db/migration:/migrations
  #   command:
  #     [
  #       "-path",
  #       "/migrations/",
  #       "-database",
  #       "postgres://${GROUP_POSTGRES_USER}:${GROUP_POSTGRES_PASSWORD}@group_service_db:5432/${GROUP_POSTGRES_USER}?sslmode=disable",
  #       "up",
  #     ]
