// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        int64
	Sender    pgtype.Text
	Receiver  pgtype.Text
	Text      pgtype.Text
	Status    pgtype.Text
	CreatedAt pgtype.Timestamp
}

type Session struct {
	Token     string
	UserLogin pgtype.Text
	Expiry    pgtype.Timestamp
}

type User struct {
	Login    string
	Username pgtype.Text
	Password pgtype.Text
}
