// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	ID        int64
	Name      pgtype.Text
	CreatedAt pgtype.Timestamp
}

type Member struct {
	GroupID     pgtype.Int8
	MemberLogin pgtype.Text
}

type Message struct {
	ID        int64
	Sender    pgtype.Text
	GroupID   pgtype.Int8
	Text      pgtype.Text
	Status    pgtype.Text
	CreatedAt pgtype.Timestamp
}
