name: static test

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        container: golang:1.21.3
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Go to gateway go module
              run: cd app
            - name: Run golangci-lint in gateway service
              uses: golangci/golangci-lint-action@v3
              with:
                version: v1.54
